### ISSUE TITLE
ошибка запуска покрытия

### ISSUE THREAD

**Issue by dilyarakhabibullina** [dilyarakhabibullina/taxiservice#6]
"C:\Program Files\Java\jdk-12\bin\java.exe" -ea -javaagent:C:\Users\днс\.IdeaIC2018.3\system\testAgent\intellij-coverage-agent-1.0.495.jar=C:\Users\днс\AppData\Local\Temp\coverage10args -Didea.test.cyclic.buffer.size=1048576 "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.5\lib\idea_rt.jar=60865:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.5\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.5\lib\idea_rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.5\plugins\junit\lib\junit-rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.5\plugins\junit\lib\junit5-rt.jar;C:\Users\днс\.m2\repository\org\junit\platform\junit-platform-launcher\1.5.1\junit-platform-launcher-1.5.1.jar;C:\Users\днс\.m2\repository\org\apiguardian\apiguardian-api\1.1.0\apiguardian-api-1.1.0.jar;C:\Users\днс\.m2\repository\org\junit\platform\junit-platform-engine\1.5.1\junit-platform-engine-1.5.1.jar;C:\Users\днс\.m2\repository\org\opentest4j\opentest4j\1.2.0\opentest4j-1.2.0.jar;C:\Users\днс\.m2\repository\org\junit\platform\junit-platform-commons\1.5.1\junit-platform-commons-1.5.1.jar;D:\JAVA_STEP_TWO\taxiservice\target\test-classes;D:\JAVA_STEP_TWO\taxiservice\target\classes;C:\Users\днс\.m2\repository\org\junit\jupiter\junit-jupiter\5.5.1\junit-jupiter-5.5.1.jar;C:\Users\днс\.m2\repository\org\junit\jupiter\junit-jupiter-api\5.5.1\junit-jupiter-api-5.5.1.jar;C:\Users\днс\.m2\repository\org\junit\jupiter\junit-jupiter-params\5.5.1\junit-jupiter-params-5.5.1.jar;C:\Users\днс\.m2\repository\org\junit\jupiter\junit-jupiter-engine\5.5.1\junit-jupiter-engine-5.5.1.jar" com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 -junit5 TaxiserviceTest
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.intellij.rt.coverage.main.CoveragePremain.premain(CoveragePremain.java:35)
	at com.intellij.rt.coverage.main.CoveragePremain.premain(CoveragePremain.java:28)
	... 6 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.intellij.rt.coverage.instrumentation.Instrumentator.performPremain(Instrumentator.java:55)
	at com.intellij.rt.coverage.instrumentation.Instrumentator.premain(Instrumentator.java:33)
	... 12 more
FATAL ERROR in native method: processing of -javaagent failed

Process finished with exit code 1
Exception in thread "main"

**Comment by coursar** [comment]
Проблема скорее всего в том, что у вас проект хранится в каталоге, где в пути есть русские символы:

C:\Users\днс.IdeaIC2018.3\
а также
C:\Users\днс.m2\
